### ISSUE TITLE
Permission denied when pulling image

### ISSUE THREAD

**Issue by rockagainstocean** [getumbrel/llama-gpt#3]
Hello, I am trying to run it on my Ubuntu machine with docker but cannot pull the image for the api: 

```
$ docker-compose up -d
Pulling llama-gpt-api (ghcr.io/getumbrel/llama-gpt-api-llama-2-7b-chat:latest)...
ERROR: Head "https://ghcr.io/v2/getumbrel/llama-gpt-api-llama-2-7b-chat/manifests/latest": denied
```

In any case, I was able to build the image and run it, so just wanted to inform about this since it's in the readme. 
Thanks for the awesome work!

**Comment by lukechilds** [comment]
Thanks! We changes the image name last minute and forget to update the compose file, fixed in https://github.com/getumbrel/llama-gpt/commit/c76225a6fc26a000fc07b074223a69b0d65b7bcf

**Comment by mitchross** [comment]
Still broken 

C:\Users\thell\Documents\Programming\llama-gpt>docker compose -f docker-compose-70b.yml up
[+] Running 2/2
 ✘ llama-gpt-ui Error                                                                                              0.5s
 ✘ llama-gpt-api-70b Error                                                                                         0.5s
Error response from daemon: Head "https://ghcr.io/v2/abetlen/llama-cpp-python/manifests/latest": denied: denied
